# Generated by Django 4.0.4 on 2022-05-27 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=256, verbose_name='Flight Number')),
                ('operating_airline', models.CharField(max_length=256, verbose_name='Operating Airline')),
                ('departure_city', models.CharField(max_length=256, verbose_name='Departure City')),
                ('arrival_city', models.CharField(max_length=256, verbose_name='Arrival City')),
                ('departure_time', models.DateTimeField(verbose_name='Departure Time')),
                ('arrival_time', models.DateTimeField(verbose_name='Arrival Time')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('capacity', models.IntegerField(verbose_name='Capacity')),
                ('available_seats', models.IntegerField(verbose_name='Available Seats')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=256, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=256, verbose_name='Phone Number')),
                ('address', models.CharField(max_length=256, verbose_name='Address')),
                ('city', models.CharField(max_length=256, verbose_name='City')),
                ('state', models.CharField(max_length=256, verbose_name='State')),
                ('zip_code', models.CharField(max_length=256, verbose_name='Zip Code')),
                ('country', models.CharField(max_length=256, verbose_name='Country')),
                ('passport_number', models.CharField(max_length=256, verbose_name='Passport Number')),
                ('passport_expiration_date', models.DateField(verbose_name='Passport Expiration Date')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flight')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=256, verbose_name='Seat Number')),
                ('seat_type', models.CharField(max_length=256, verbose_name='Seat Type')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.passenger')),
            ],
        ),
    ]
