# Generated by Django 4.0.4 on 2022-05-27 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_alter_passenger_flight_alter_reservation_flight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='flight',
        ),
    ]
